// export const createProductsList = () => {
//   let productsList = [];
//   let categoryList = ["home", "milk products", "kan", "baby", "drink"];
//   const characters = "abcdefghijklmnopqrstuvwxyz";
//   let name = "";
//   let price = 0;
//   for (let i = 0; i < 100; i++) {
//     const randomCategory = Math.floor(Math.random() * categoryList.length);
//     const Amount = Math.floor(Math.random() * 100) + 2;
//     price = Math.floor(Math.random() * 1000) + 10;
//     let nameLength = Math.floor(Math.random() * 6) + 3;
//     for (let j = 0; j < nameLength; j++) {
//       name += characters.charAt(Math.floor(Math.random() * characters.length));
//     }
//     productsList.push({
//       Name: name,
//       Price: price,
//       Category: categoryList[randomCategory],
//       Amount,
//       Description:
//         "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
//       Img: "https://via.placeholder.com/600/771796",
//     });
//     name = "";
//   }
//   return productsList;
// };

// let allProducts = createProductsList();
// const allProductsJson = JSON.stringify(allProducts);
// console.log(allProductsJson)

export default[
  {
    Name: "hqb",
    Price: 451,
    Category: "kan",
    Amount: 40,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "rnrp",
    Price: 912,
    Category: "drink",
    Amount: 2,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "vnjyctb",
    Price: 928,
    Category: "drink",
    Amount: 49,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "mkuqimsx",
    Price: 308,
    Category: "kan",
    Amount: 101,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "hakcdn",
    Price: 198,
    Category: "kan",
    Amount: 21,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ozebdzr",
    Price: 129,
    Category: "kan",
    Amount: 75,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ybbm",
    Price: 969,
    Category: "home",
    Amount: 10,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "mqwblhp",
    Price: 59,
    Category: "kan",
    Amount: 70,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "npxowg",
    Price: 350,
    Category: "kan",
    Amount: 49,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "uhlo",
    Price: 292,
    Category: "home",
    Amount: 13,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "uibpi",
    Price: 74,
    Category: "drink",
    Amount: 82,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "bast",
    Price: 512,
    Category: "home",
    Amount: 63,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "gbioamtd",
    Price: 189,
    Category: "baby",
    Amount: 91,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "hwpwz",
    Price: 634,
    Category: "milk products",
    Amount: 40,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "xdfxn",
    Price: 904,
    Category: "baby",
    Amount: 90,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ookyqv",
    Price: 346,
    Category: "home",
    Amount: 99,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ealvt",
    Price: 650,
    Category: "drink",
    Amount: 35,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ywcwgm",
    Price: 578,
    Category: "baby",
    Amount: 72,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "jcjfka",
    Price: 448,
    Category: "drink",
    Amount: 50,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "yek",
    Price: 92,
    Category: "milk products",
    Amount: 2,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "nveovtco",
    Price: 835,
    Category: "milk products",
    Amount: 21,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "zouxckqm",
    Price: 880,
    Category: "kan",
    Amount: 97,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "dyzzyeyd",
    Price: 652,
    Category: "milk products",
    Amount: 18,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fooyng",
    Price: 315,
    Category: "kan",
    Amount: 98,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "flmtjo",
    Price: 30,
    Category: "drink",
    Amount: 38,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "zfjczbd",
    Price: 529,
    Category: "home",
    Amount: 23,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "lxahsdll",
    Price: 881,
    Category: "kan",
    Amount: 61,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "wxe",
    Price: 213,
    Category: "home",
    Amount: 24,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ubu",
    Price: 678,
    Category: "home",
    Amount: 99,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ckjfvrjc",
    Price: 129,
    Category: "drink",
    Amount: 54,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "drkwqd",
    Price: 845,
    Category: "milk products",
    Amount: 62,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "luuhvwft",
    Price: 24,
    Category: "drink",
    Amount: 73,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "mpui",
    Price: 183,
    Category: "drink",
    Amount: 56,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "zidphk",
    Price: 242,
    Category: "kan",
    Amount: 100,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "wzsir",
    Price: 504,
    Category: "drink",
    Amount: 34,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "mssgy",
    Price: 59,
    Category: "baby",
    Amount: 51,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "nfwy",
    Price: 178,
    Category: "kan",
    Amount: 56,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fljzw",
    Price: 147,
    Category: "milk products",
    Amount: 47,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "xjfbuj",
    Price: 846,
    Category: "milk products",
    Amount: 66,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "unteu",
    Price: 746,
    Category: "milk products",
    Amount: 89,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "cxd",
    Price: 424,
    Category: "kan",
    Amount: 94,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "dqc",
    Price: 255,
    Category: "drink",
    Amount: 45,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "czpykun",
    Price: 77,
    Category: "home",
    Amount: 6,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "cdghy",
    Price: 549,
    Category: "baby",
    Amount: 65,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "nqehm",
    Price: 704,
    Category: "milk products",
    Amount: 93,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "exc",
    Price: 156,
    Category: "drink",
    Amount: 39,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "omexfft",
    Price: 443,
    Category: "drink",
    Amount: 44,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "wtynvn",
    Price: 983,
    Category: "baby",
    Amount: 62,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "tgicie",
    Price: 168,
    Category: "baby",
    Amount: 54,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ilfrrzt",
    Price: 657,
    Category: "drink",
    Amount: 82,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "zxx",
    Price: 475,
    Category: "milk products",
    Amount: 27,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "mrokyjgj",
    Price: 34,
    Category: "kan",
    Amount: 73,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "qftrbvp",
    Price: 247,
    Category: "home",
    Amount: 2,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "egcby",
    Price: 130,
    Category: "drink",
    Amount: 44,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "qxpfcuzt",
    Price: 665,
    Category: "milk products",
    Amount: 97,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "wcpp",
    Price: 710,
    Category: "home",
    Amount: 32,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "kzp",
    Price: 942,
    Category: "drink",
    Amount: 84,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "jvlf",
    Price: 467,
    Category: "milk products",
    Amount: 85,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fxmraz",
    Price: 939,
    Category: "kan",
    Amount: 72,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "aoqpezxf",
    Price: 274,
    Category: "baby",
    Amount: 18,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "wmmugaxk",
    Price: 87,
    Category: "milk products",
    Amount: 83,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "nkg",
    Price: 372,
    Category: "home",
    Amount: 82,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "elq",
    Price: 964,
    Category: "kan",
    Amount: 6,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "qzyqzdll",
    Price: 837,
    Category: "drink",
    Amount: 75,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fsruwwek",
    Price: 895,
    Category: "home",
    Amount: 99,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "cnu",
    Price: 12,
    Category: "baby",
    Amount: 3,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "zjatk",
    Price: 217,
    Category: "baby",
    Amount: 40,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "hrvmz",
    Price: 707,
    Category: "baby",
    Amount: 2,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "sglwfrq",
    Price: 161,
    Category: "kan",
    Amount: 41,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "uwno",
    Price: 681,
    Category: "milk products",
    Amount: 30,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ixyyyou",
    Price: 534,
    Category: "drink",
    Amount: 3,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "aqlxwf",
    Price: 732,
    Category: "home",
    Amount: 97,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "qeetpqtk",
    Price: 402,
    Category: "baby",
    Amount: 37,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "dwmdfp",
    Price: 154,
    Category: "drink",
    Amount: 56,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fcg",
    Price: 297,
    Category: "baby",
    Amount: 50,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "nfmeqf",
    Price: 146,
    Category: "baby",
    Amount: 87,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "dosiyjzh",
    Price: 694,
    Category: "kan",
    Amount: 99,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ixccns",
    Price: 423,
    Category: "baby",
    Amount: 82,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "exlejw",
    Price: 694,
    Category: "drink",
    Amount: 89,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "kafrcs",
    Price: 175,
    Category: "drink",
    Amount: 80,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "xlsp",
    Price: 621,
    Category: "kan",
    Amount: 76,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ghily",
    Price: 265,
    Category: "home",
    Amount: 23,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "fmrozgfk",
    Price: 554,
    Category: "home",
    Amount: 76,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "dpxul",
    Price: 941,
    Category: "home",
    Amount: 5,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ybljffq",
    Price: 828,
    Category: "drink",
    Amount: 3,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ppzv",
    Price: 756,
    Category: "kan",
    Amount: 28,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "atfukqk",
    Price: 486,
    Category: "home",
    Amount: 88,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "akjey",
    Price: 556,
    Category: "drink",
    Amount: 44,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "jqolizpj",
    Price: 55,
    Category: "home",
    Amount: 73,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "jaw",
    Price: 110,
    Category: "baby",
    Amount: 100,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "rzflsb",
    Price: 325,
    Category: "milk products",
    Amount: 41,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ttvonbae",
    Price: 542,
    Category: "kan",
    Amount: 65,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "skqrv",
    Price: 220,
    Category: "baby",
    Amount: 42,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "ltna",
    Price: 662,
    Category: "drink",
    Amount: 66,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "onfmqry",
    Price: 800,
    Category: "milk products",
    Amount: 6,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "jgvkzlpl",
    Price: 982,
    Category: "milk products",
    Amount: 45,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "lagtaqi",
    Price: 365,
    Category: "kan",
    Amount: 36,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "sleo",
    Price: 870,
    Category: "milk products",
    Amount: 82,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "yllqdics",
    Price: 749,
    Category: "drink",
    Amount: 61,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  },
  {
    Name: "imddhv",
    Price: 71,
    Category: "milk products",
    Amount: 79,
    Description: "aaaaaansahisac asnuas asndisal jlansd jnsada adna knsad knad",
    Img: "https://via.placeholder.com/600/771796",
  }
];
